export const colors = {
  primary: '#154212',
  primaryContainer: '#2d5a27',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#9dd090',
  primaryFixed: '#bcf0ae',
  onPrimaryFixed: '#002201',
  onPrimaryFixedVariant: '#23501e',
  secondary: '#944925',
  secondaryContainer: '#fe9e72',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#773310',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  surface: '#fbfbe2',
  surfaceDim: '#dbdcc3',
  onSurface: '#1b1d0e',
  surfaceLowest: '#ffffff',
  surfaceLow: '#f5f5dc',
  surfaceContainer: '#efefd7',
  surfaceHigh: '#eaead1',
  surfaceHighest: '#e4e4cc',
  onSurfaceVariant: '#42493e',
  outline: '#72796e',
  outlineVariant: '#c2c9bb',
}
